### ISSUE TITLE
Candy should respond to XMPP application-lecel pings (XEP-0199)

### ISSUE THREAD

**Issue by michalrus** [candy-chat/candy#517]
https://xmpp.org/extensions/xep-0199.html

Currently, it doesn’t, and the client is disconnected by a server that requires this.

**Comment by lkraav** [comment]
@michalrus example of such server?

I'm running on Openfire, and haven't noticed any unnatural disconnects.

**Comment by michalrus** [comment]
@lkraav any Ejabberd with this in its config:

```yaml
          mod_ping:
            send_pings: true
            ping_interval: 20
            ping_ack_timeout: 20
            timeout_action: kill
```

Cf. https://docs.ejabberd.im/admin/configuration/#mod-ping
